#!/usr/bin/env python3
"""Paper B: the LaTeX macros and table fragments, generated from
paperB/FROZEN.json. Every number the manuscript prints is a macro defined
here; none is typed into the prose (the standing rule after Paper IV).

    .venv/bin/python docs/paperB/latex_tables.py      # writes numbers.tex, tab_*.tex
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FROZEN = ROOT / "paperB/FROZEN.json"
IONS = ("57LaII", "58CeII", "60NdII")
SHORT = {"57LaII": "La", "58CeII": "Ce", "60NdII": "Nd"}


def f2(v): return f"{v:.2f}"
def f3(v): return f"{v:.3f}"
def f1(v): return f"{v:.1f}"
def pct0(v): return f"{100 * v:.0f}\\%"
def intv(v): return f"{int(round(v))}"
def com(v): return f"{int(round(v)):,}".replace(",", "{,}")
def word(v): return str(v)
def wordlow(v): return str(v).lower()


FMT = dict(f1=f1, f2=f2, f3=f3, pct0=pct0, int=intv, com=com, word=word, wordlow=wordlow)


def _g1(h, ion, key):
    return h["g1"]["per_ion"][ion][key]


def macros(h):
    """[(name, value, fmt)] -- the name is the LaTeX macro without backslash."""
    out = []
    out.append(("PBdmMax", h["g1"]["dm_max"], "f2"))
    out.append(("PBdcolMax", h["g1"]["dcolour_max"], "f2"))
    out.append(("PBGoneB", h["g1"]["B1"], "word"))
    out.append(("PBGoneDecision", h["g1"]["decision"], "word"))
    out.append(("PBGtwoHone", h["g2"]["H1"], "word"))
    out.append(("PBGtwoHtwo", h["g2"]["H2"], "word"))
    for ion in IONS:
        s = SHORT[ion]
        out += [(f"PB{s}NgStar", _g1(h, ion, "ng_star"), "int"),
                (f"PB{s}EpsStar", _g1(h, ion, "eps_star"), "f2"),
                (f"PB{s}EpsErr", _g1(h, ion, "eps_max_dm"), "f2"),
                (f"PB{s}Rerr", _g1(h, ion, "e_R"), "f3"),
                (f"PB{s}EvPerPkt", _g1(h, ion, "events_per_packet"), "f1"),
                (f"PB{s}Klocal", h["g2"]["per_ion"][ion]["k_local"], "int"),
                (f"PB{s}Lstar", h["g2"]["per_ion"][ion]["L_star"], "f3"),
                (f"PB{s}Shift", abs(h["r2m"]["per_ion"][ion]["shift_max"]), "f2"),
                (f"PB{s}Rebuilt", h["r2m"]["per_ion"][ion]["rebuilt_band"], "f3"),
                (f"PB{s}Downward", h["r2m"]["per_ion"][ion]["downward_band"], "f2"),
                (f"PB{s}Survives", h["r2m"]["per_ion"][ion]["survives"], "wordlow"),
                (f"PB{s}NExit", h["audit"]["per_ion"][ion]["n_exit"], "com"),
                (f"PB{s}NLines", h["audit"]["per_ion"][ion]["n_lines"], "com"),
                (f"PB{s}KbTables", h["audit"]["per_ion"][ion]["kb_tables"], "int"),
                (f"PB{s}Conc", h["audit"]["per_ion"][ion]["conc90"], "com")]
        c = h["g2"]["contrast"][ion]
        out += [(f"PB{s}EventGlobal", c["event_global"], "f3"), (f"PB{s}EventLocal", c["event_local"], "f3"),
                (f"PB{s}BandGlobal", c["band_global"], "f3"), (f"PB{s}BandLocal", c["band_local"], "f3"),
                (f"PB{s}EventRatio", c["event_ratio"], "f1"), (f"PB{s}BandRatio", c["band_ratio"], "f1")]
        kg = h["g2"]["per_ion"][ion]["k_global"]
        out.append((f"PB{s}Kglobal", "undefined" if kg is None else str(int(kg)), "word"))
    out.append(("PBContrastK", h["g2"]["contrast"][IONS[0]]["k"], "int"))
    out.append(("PBParamsGlobal", h["g2"]["contrast"][IONS[0]]["params_global"], "com"))
    out.append(("PBParamsLocal", h["g2"]["contrast"][IONS[0]]["params_local"], "com"))
    return out


def numbers_tex(h):
    lines = ["% generated by docs/paperB/latex_tables.py from paperB/FROZEN.json -- do not edit"]
    for name, val, fmt in macros(h):
        lines.append(f"\\newcommand{{\\{name}}}{{{FMT[fmt](val)}}}")
    return "\n".join(lines) + "\n"


def tab_gates(h):
    """The result table: per ion, G1's N_g* and eps*, G2's counts, H2's L*."""
    L = ["% generated by docs/paperB/latex_tables.py -- do not edit",
         "\\begin{tabular}{lccccccc}", "\\hline",
         "ion & $N_g^\\star$ & $\\epsilon^\\star$ & error at $\\epsilon^\\star$ & $K^\\star_{\\rm local}$ & "
         "$K^\\star_{\\rm global}$ & $L^\\star$ & $R_8$ vs the new reference \\\\",
         " & & & [mag] & & & & [mag] \\\\", "\\hline"]
    for ion in IONS:
        s = SHORT[ion]
        L.append(f"{h['ion_names'][ion]} & \\PB{s}NgStar & \\PB{s}EpsStar & \\PB{s}EpsErr & \\PB{s}Klocal & "
                 f"\\PB{s}Kglobal & \\PB{s}Lstar & \\PB{s}Rebuilt \\\\")
    L += ["\\hline", "\\end{tabular}"]
    return "\n".join(L) + "\n"


def tab_contrast(h):
    """The mechanism table: events against observables at 32 archetypes."""
    L = ["% generated by docs/paperB/latex_tables.py -- do not edit",
         "\\begin{tabular}{lcccc}", "\\hline",
         "ion & $m_{\\rm event}$ global & $m_{\\rm event}$ local & max $|\\Delta m|$ global & max $|\\Delta m|$ local \\\\",
         " & & & [mag] & [mag] \\\\", "\\hline"]
    for ion in IONS:
        s = SHORT[ion]
        L.append(f"{h['ion_names'][ion]} & \\PB{s}EventGlobal & \\PB{s}EventLocal & \\PB{s}BandGlobal & \\PB{s}BandLocal \\\\")
    L += ["\\hline", "\\end{tabular}"]
    return "\n".join(L) + "\n"


def main():
    h = json.loads(FROZEN.read_text())
    written = []
    for name, text in (("numbers.tex", numbers_tex(h)), ("tab_gates.tex", tab_gates(h)), ("tab_contrast.tex", tab_contrast(h))):
        p = HERE / name; p.write_text(text); written.append(p)
    return written


if __name__ == "__main__":
    for p in main():
        print("wrote", p)
