#!/usr/bin/env python3
"""numbers.tex and the table fragments of the Paper IV manuscript from
paper4/FROZEN.json (regenerated by paper4/freeze.py from the run records).
Every number the manuscript quotes is a macro defined here; rounding
happens here only. `quoted` macros must be used in the prose (checked by
check_structure.py)."""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FROZEN = ROOT / "paper4/FROZEN.json"
BANDS = "grizJHK"


def _get(h, key):
    v = h
    for k in key.split("."):
        v = v[k]
    return v


def f1(v): return f"{v:.1f}"
def f2(v): return f"{v:.2f}"
def f3(v): return f"{v:.3f}"
def sf2(v): return f"{v:+.2f}"
def pct0(v): return f"{100 * v:.0f}\\%"
def pct1(v): return f"{100 * v:.1f}\\%"
def sci(v):
    m, e = f"{v:.2e}".split("e"); return f"{m} \\times 10^{{{int(e)}}}"
def sci1(v):
    m, e = f"{v:.1e}".split("e"); return f"{m} \\times 10^{{{int(e)}}}"
def rng2(v): return f"{v[0]:.2f}--{v[1]:.2f}"
def rngabs2(v):
    lo, hi = sorted(abs(x) for x in v); return f"{lo:.2f}--{hi:.2f}"
def intv(v): return f"{int(round(v))}"
def word(v): return str(v)

FMT = dict(f1=f1, f2=f2, f3=f3, sf2=sf2, pct0=pct0, pct1=pct1, sci=sci, sci1=sci1, rng2=rng2, rngabs2=rngabs2, int=intv, word=word)

# (macro, key into FROZEN["headline"] or a callable of headline, format, quoted)
MACROS = [
    # the corrected closures on published states (F60, F61)
    ("BtwoRtwoZPone", lambda h: [h["summary"]["B2_R2_z_P1_min"], h["summary"]["B2_R2_z_P1_max"]], "rngabs2", True),
    ("BtwoRtwoKPone", lambda h: [h["summary"]["B2_R2_K_P1_min"], h["summary"]["B2_R2_K_P1_max"]], "rngabs2", True),
    ("BtwoRtwoPtwoG", "summary.B2_R2_P2_g", "sf2", True),
    ("BbinRtwoPone", lambda h: [h["summary"]["Bbin2_R2_P1_min"], h["summary"]["Bbin2_R2_P1_max"]], "rng2", True),
    ("BbinthRthPoneAbsmax", "summary.Bbinth_Rth_P1_absmax", "f2", True),
    ("BthRthPone", lambda h: [h["summary"]["Bth_Rth_P1_min"], h["summary"]["Bth_Rth_P1_max"]], "rngabs2", True),
    ("AtwoRtwoAbsmax", "summary.A2_R2_absmax", "f2", True),
    ("BoneRoneAbsmax", "summary.B1_R1_P1_t2_absmax_zK", "f2", True),
    ("RoneRtwoZ", "summary.R1_R2_P1_t2_z", "f2", True),
    # grid invariance (F60)
    ("GridFourZ", "grid.shells4.B2_R2.z", "sf2", True),
    ("GridTwelveZ", "grid.shells12.B2_R2.z", "sf2", True),
    ("GridTwentythreeZ", "grid.shells23.B2_R2.z", "sf2", True),
    ("GridSingleZ", "grid.single_s28.B2_R2.z", "sf2", True),
    ("ConvZ", lambda h: [h["convergence"]["B2_R2_z_min"], h["convergence"]["B2_R2_z_max"]], "rngabs2", True),
    ("ConvNsettings", "convergence.n_settings", "int", False),
    # the macroatom test (F63)
    ("MacroRefShiftG", "macro.R2M_R2.g", "sf2", True),
    ("MacroBtwoZ", "macro.B2M_R2M.z", "sf2", True),
    ("MacroBtwoAbsmax", lambda h: max(abs(v) for v in h["macro"]["B2M_R2M"].values()), "f2", True),
    ("MacroBbinG", "macro.Bbin2M_R2M.g", "sf2", True),
    ("MacroBbinK", "macro.Bbin2M_R2M.K", "sf2", True),
    ("MacroEvRatio", lambda h: h["macro"]["ev_R2M"] / h["macro"]["ev_R2"], "f1", True),
    # the Fontes snapshot (F64)
    ("FontesEpsBthRthRK", "fontes_snapshot.gsi_reflect.Bth_Rth_rK", "sf2", True),
    ("FontesEpsBbinRthRK", "fontes_snapshot.gsi_reflect.Bbinth_Rth_rK", "sf2", True),
    ("FontesFluBtwoRtwoRK", "fontes_snapshot.gsi_reflect.B2_R2_rK", "sf2", True),
    ("FontesFluBbinRtwoRK", "fontes_snapshot.gsi_reflect.Bbin2_R2_rK", "sf2", True),
    ("FontesFluBbinRtwoRKreemit", "fontes_snapshot.gsi_reemit.Bbin2_R2_rK", "sf2", True),
    ("FontesJpltEpsBbinRthRK", "fontes_snapshot.jplt_reflect.Bbinth_Rth_rK", "sf2", True),
    ("FontesJpltNlines", "fontes_snapshot.jplt_reflect.n_lines", "int", True),
    ("FontesGsiNlines", "fontes_snapshot.gsi_reflect.n_lines", "int", True),
    # the light curve (F65)
    ("LcSlabs", "lightcurve.n_slabs", "int", True),
    ("LcRthPeakD", "lightcurve.legs.Rth.t_peak_d", "f2", True),
    ("LcRtwoPeakD", "lightcurve.legs.R2.t_peak_d", "f2", True),
    ("LcBthDL", "lightcurve.legs.Bth.dL_peak", "pct0", True),
    ("LcBbinthDL", "lightcurve.legs.Bbinth.dL_peak", "pct1", True),
    ("LcBtwoDL", "lightcurve.legs.B2.dL_peak", "pct0", True),
    ("LcBbintwoDL", "lightcurve.legs.Bbin2.dL_peak", "pct1", True),
    ("LcBthColour", "lightcurve.legs.Bth.max_abs_dcolour", "f2", True),
    ("LcBbinthColour", "lightcurve.legs.Bbinth.max_abs_dcolour", "f2", True),
    ("LcBtwoColour", "lightcurve.legs.B2.max_abs_dcolour", "f2", True),
    ("LcBbintwoColour", "lightcurve.legs.Bbin2.max_abs_dcolour", "f2", True),
    ("LcBbintwoHmax", "lightcurve.legs.Bbin2.max_abs_dm.H", "f2", True),
    ("LcBbintwoCapped", "lightcurve.legs.Bbin2.f_capped_max", "pct1", True),
    ("LcWfrac", lambda h: h["lightcurve"]["legs"]["R2"]["W_tot"] / (h["lightcurve"]["legs"]["R2"]["E_init"] + h["lightcurve"]["legs"]["R2"]["E_inj"]), "pct0", True),
    ("LcEradFrac", lambda h: h["lightcurve"]["legs"]["R2"]["E_rad"] / (h["lightcurve"]["legs"]["R2"]["E_init"] + h["lightcurve"]["legs"]["R2"]["E_inj"]), "pct0", True),
    ("LcInitHeatRatio", lambda h: h["lightcurve"]["legs"]["R2"]["E_init"] / h["lightcurve"]["legs"]["R2"]["E_inj"], "f1", True),
    ("LcRadRtwoPeakD", "lightcurve.rad_variant.R2.t_peak_d", "f1", True),
    ("LcRadBtwoDL", "lightcurve.rad_variant.B2.dL_peak", "pct0", True),
    ("LcRadBtwoColour", "lightcurve.rad_variant.B2.max_abs_dcolour", "f2", True),
    # the P1-xkn transport replacement test (F66)
    ("PxSlabs", "lightcurve_p1xkn.n_slabs", "int", True),
    ("PxXphFirst", "lightcurve_p1xkn.zone.x_ph_first", "f2", True),
    ("PxXphLast", "lightcurve_p1xkn.zone.x_ph_last", "f2", True),
    ("PxTphFirst", "lightcurve_p1xkn.zone.T_ph_first", "int", True),
    ("PxTphLast", "lightcurve_p1xkn.zone.T_ph_last", "int", True),
    ("PxZoneFirst", "lightcurve_p1xkn.zone.n_zone_first", "int", True),
    ("PxZoneLast", "lightcurve_p1xkn.zone.n_zone_last", "int", True),
    ("PxHeatFrac", lambda h: 1.0 - h["lightcurve_p1xkn"]["zone"]["core_frac_first"], "pct1", True),
    ("PxRtwoPeakD", "lightcurve_p1xkn.legs.R2.t_peak_d", "f2", True),
    ("PxBtwoDL", lambda h: abs(h["lightcurve_p1xkn"]["legs"]["B2"]["dL_peak"]), "pct1", True),
    ("PxBbintwoDL", lambda h: abs(h["lightcurve_p1xkn"]["legs"]["Bbin2"]["dL_peak"]), "pct1", True),
    ("PxNoise", "lightcurve_p1xkn.readings.R2_fluorescence_peaks.noise", "pct1", True),
    ("PxBtwoI", "lightcurve_p1xkn.legs.B2.median_dm.i", "sf2", True),
    ("PxBtwoK", "lightcurve_p1xkn.legs.B2.median_dm.K", "sf2", True),
    ("PxBbintwoI", "lightcurve_p1xkn.legs.Bbin2.median_dm.i", "sf2", True),
    ("PxBbintwoK", "lightcurve_p1xkn.legs.Bbin2.median_dm.K", "sf2", True),
    ("PxBtwoIK", "lightcurve_p1xkn.legs.B2.median_diK", "sf2", True),
    ("PxBbintwoIK", "lightcurve_p1xkn.legs.Bbin2.median_diK", "sf2", True),
    ("PxBtwoJK", "lightcurve_p1xkn.legs.B2.median_dJK", "sf2", True),
    ("PxBbintwoJK", "lightcurve_p1xkn.legs.Bbin2.median_dJK", "sf2", True),
    ("PxBtwoColour", "lightcurve_p1xkn.legs.B2.max_abs_dcolour", "f2", True),
    ("PxBbintwoColour", "lightcurve_p1xkn.legs.Bbin2.max_abs_dcolour", "f2", True),
    ("PxEvFirst", "lightcurve_p1xkn.legs.R2.events_mean_first", "f1", True),
    ("PxEvLast", "lightcurve_p1xkn.legs.R2.events_mean_last", "f1", True),
    ("PxWfirst", "lightcurve_p1xkn.legs.R2.W_over_esc_first", "pct0", True),
    ("PxBbinEvLast", "lightcurve_p1xkn.legs.Bbin2.events_mean_last", "int", True),
    ("PxConvErad", lambda h: abs(h["lightcurve_p1xkn"]["controls"]["conv10"]["E_rad"] / h["lightcurve_p1xkn"]["controls"]["conv5"]["E_rad"] - 1), "pct1", True),
    ("PxConvW", lambda h: abs(h["lightcurve_p1xkn"]["controls"]["conv10"]["W_tot"] / h["lightcurve_p1xkn"]["controls"]["conv5"]["W_tot"] - 1), "pct1", True),
    ("PxFreeRatioMax", "lightcurve_p1xkn.controls.free.L_ratio_max_after", "f2", True),
    ("PxFreeRatioMin", "lightcurve_p1xkn.controls.free.L_ratio_min_after", "f2", True),
]


def macros(h):
    out = []
    for name, key, fmt, _ in MACROS:
        try:
            v = key(h) if callable(key) else _get(h, key)
        except (KeyError, TypeError):
            continue                                  # a record not yet present (e.g. the P1 light curve)
        out.append((name, FMT[fmt](v)))
    names = [n for n, _ in out]
    assert len(names) == len(set(names)), "duplicate macro name"
    return out


def quoted_names(h):
    present = {n for n, _ in macros(h)}
    return [name for name, _, _, q in MACROS if q and name in present]


def numbers_tex(h):
    lines = ["% generated by docs/paper4/latex_tables.py from paper4/FROZEN.json -- do not edit",
             "% every number the manuscript quotes; rounding happens here only"]
    lines += [f"\\newcommand{{\\{n}}}{{{t}\\xspace}}" for n, t in macros(h)]
    return "\n".join(lines) + "\n"


def tab_lightcurve(h):
    lc = h["lightcurve"]["legs"]
    name = dict(Rth="resolved", Bth="expansion", Bbinth="line-binned", R2="resolved", B2="expansion", Bbin2="line-binned")
    rows = []
    for leg in ("Rth", "Bth", "Bbinth", "R2", "B2", "Bbin2"):
        if leg not in lc:
            continue
        o = lc[leg]; red = "$\\epsilon = 1$" if leg.endswith("th") else "fluorescence"
        dl = f"{100 * o['dL_peak']:+.0f}\\%" if "dL_peak" in o else "--"
        col = f"{o['max_abs_dcolour']:.2f}" if "max_abs_dcolour" in o else "--"
        rows.append(f"{name[leg]} & {red} & {o['t_peak_d']:.2f} & {o['L_peak'] / 1e40:.2f} & {o['E_rad'] / 1e46:.3f} & {o['W_tot'] / 1e46:.3f} & {dl} & {col} \\\\")
    return "\n".join([
        "% generated by docs/paper4/latex_tables.py -- do not edit",
        "\\begin{tabular}{llrrrrrr}", "\\hline",
        "opacity & redistribution & $t_{\\rm peak}$ (d) & $L_{\\rm peak}$ ($10^{40}$ erg s$^{-1}$) & $E_{\\rm rad}$ ($10^{46}$ erg) & $W$ ($10^{46}$ erg) & $\\Delta L_{\\rm peak}$ & max $|\\Delta$colour$|$ (mag) \\\\",
        "\\hline", *rows, "\\hline", "\\end{tabular}"]) + "\n"


def tab_grid(h):
    g = h["grid"]
    rows = []
    for tag, label in (("single_s27", "single zone, shell 27"), ("single_s28", "single zone, photospheric shell"), ("single_s29", "single zone, shell 29"),
                       ("shells4", "4 transported shells"), ("split3", "4 shells, one split in three"), ("shells6", "6 shells"),
                       ("shells12", "12 shells"), ("shells23", "23 shells")):
        b = g[tag]["B2_R2"]; bb = g[tag]["Bbin2_R2"]
        rows.append(f"{label} & {b['g']:+.2f} & {b['z']:+.2f} & {b['K']:+.2f} & {bb['g']:+.2f} & {bb['z']:+.2f} & {bb['K']:+.2f} \\\\")
    return "\n".join([
        "% generated by docs/paper4/latex_tables.py -- do not edit",
        "\\begin{tabular}{lrrrrrr}", "\\hline",
        "P1, 2 d & $B_2 - R_2$ (g) & (z) & (K) & $B_{\\rm bin,2} - R_2$ (g) & (z) & (K) \\\\", "\\hline", *rows, "\\hline", "\\end{tabular}"]) + "\n"


def tab_matrix(h):
    rows = []
    for key in ("P1_t1", "P1_t2", "P1_t3", "P1_t5", "P1r1_t2", "P1r2_t2", "P2_t3.4"):
        s = h["states"][key]
        def trip(d): return f"{d['g']:+.2f} / {d['z']:+.2f} / {d['K']:+.2f}"
        rows.append(f"{s['name']} & {trip(s['Bth_Rth'])} & {trip(s['Bbinth_Rth'])} & {trip(s['B2_R2'])} & {trip(s['Bbin2_R2'])} \\\\")
    return "\n".join([
        "% generated by docs/paper4/latex_tables.py -- do not edit",
        "\\begin{tabular}{lcccc}", "\\hline",
        "state & expansion, $\\epsilon=1$ & line-binned, $\\epsilon=1$ & expansion, fluor. & line-binned, fluor. \\\\",
        " & \\multicolumn{4}{c}{closure $-$ resolved, $g$ / $z$ / $K$ (mag)} \\\\", "\\hline", *rows, "\\hline", "\\end{tabular}"]) + "\n"


def tab_p1xkn(h):
    if "lightcurve_p1xkn" not in h:
        return "% no P1-xkn record\n"
    lc = h["lightcurve_p1xkn"]["legs"]; name = dict(R2="resolved", B2="expansion", Bbin2="line-binned")
    rows = []
    for leg in ("R2", "B2", "Bbin2"):
        o = lc[leg]
        dl = f"{100 * o['dL_peak']:+.1f}\\%" if o.get("dL_peak") is not None else "--"
        if "median_dm" in o:
            md = o["median_dm"]; cols = f"{md['i']:+.2f} & {md['z']:+.2f} & {md['J']:+.2f} & {md['K']:+.2f} & {o['median_diK']:+.2f} & {o['median_dJK']:+.2f}"
        else:
            cols = "-- & -- & -- & -- & -- & --"
        rows.append(f"{name[leg]} & {o['t_peak_d']:.2f} & {o['L_peak'] / 1e40:.2f} & {o['E_rad'] / 1e46:.3f} & {o['W_tot'] / 1e44:.2f} & {dl} & {cols} \\\\")
    return "\n".join([
        "% generated by docs/paper4/latex_tables.py -- do not edit",
        "\\begin{tabular}{lrrrrrrrrrrr}", "\\hline",
        "treatment & $t_{\\rm peak}$ (d) & $L_{\\rm peak}$ ($10^{40}$) & $E_{\\rm rad}$ ($10^{46}$) & $W$ ($10^{44}$) & $\\Delta L_{\\rm peak}$ & $\\Delta i$ & $\\Delta z$ & $\\Delta J$ & $\\Delta K$ & $\\Delta(i-K)$ & $\\Delta(J-K)$ \\\\",
        " & & erg s$^{-1}$ & erg & erg & & \\multicolumn{6}{c}{median over the photometric bins, closure $-$ resolved (mag)} \\\\",
        "\\hline", *rows, "\\hline", "\\end{tabular}"]) + "\n"


def main():
    h = json.loads(FROZEN.read_text())["headline"]
    (HERE / "numbers.tex").write_text(numbers_tex(h))
    (HERE / "tab_lightcurve.tex").write_text(tab_lightcurve(h))
    (HERE / "tab_grid.tex").write_text(tab_grid(h))
    (HERE / "tab_matrix.tex").write_text(tab_matrix(h))
    (HERE / "tab_p1xkn.tex").write_text(tab_p1xkn(h))
    print(f"wrote numbers.tex ({len(macros(h))} macros) and 4 table fragments")


if __name__ == "__main__":
    main()
